version: "3.5"
services:

  hadoop:
    build:
      context: .
      dockerfile: Dockerfile
    image: hadoop:1.0
    container_name: hadoop
    hostname: hadoop
    ports:
      - "8088:8088"
      - "9000:9000"
      - "9864:9864"
      - "9870:9870"
    stdin_open: true
    tty: true        
    networks:
      eth0:
        ipv4_address: 192.168.43.2

networks:
  eth0:
    name: eth0
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.43.0/26
